.\" This is the manpage for cw1-6005-ms42g11
.\" Copyright (C) 2012 Michael Steiakakis ms42g11@ecs.soton.ac.uk
.TH man 1 "21th February 2012" "1.0" "cw1-6005-ms42g11 man page"
.SH NAME
news \- Reads RSS feeds from : bbc.co.uk
.SH SYNOPSIS
.B news [--feeds] [--items]
.SH DESCRIPTION
This program is a command-line-interface RSS feed reader, that retrieves rss feeds from http://feeds.bbci.co.uk/news/rss.xml
.SH OPTIONS
.IP --feeds
Gives custom RSS feed(s) URLs ending in .xml seperated by space.
.IP --items
Gives how many items of the custom feeds you wish to display at one time.
.IP --help
Gives the help text for using this package

.SH BUGS
Non
.SH EXIT MANUAL
Press: wq
.SH AUTHOR
Michael Steiakakis (ms42g11@ecs.soton.ac.uk)
.SH SEE ALSO
https://github.com/mstiak/Info6005Cw1Ms42g11
